[project]
name = "gitpurge"
version = "0.1.0"
description = "VSCode extension for real-time detection of secrets and sensitive information before they get committed to Git."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
gitpurge = "gitpurge.server:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
